# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev-hello-world',
                'doc_host': 'https://SBrewer15.github.io',
                'git_url': 'https://github.com/SBrewer15/nbdev-hello-world',
                'lib_path': 'nbdev_hello_world'},
  'syms': { 'nbdev_hello_world.core': { 'nbdev_hello_world.core.foo': ( 'https://SBrewer15.github.io/core.html#foo',
                                                                        'https://github.com/SBrewer15/nbdev-hello-world/blob/master/nbdev_hello_world/core.py#L7')}}}